FROM python:3.9-slim


ARG DBT_DEV_DB_NAME
ARG DBT_DEV_HOST
ARG DBT_DEV_PASSWORD
ARG DBT_DEV_USER
ARG DBT_DEV_SCHEMA
ARG DBT_DEV_PORT

ENV DBT_DEV_DB_NAME=$DBT_DEV_DB_NAME
ENV DBT_DEV_HOST=$DBT_DEV_HOST
ENV DBT_DEV_PASSWORD=$DBT_DEV_PASSWORD
ENV DBT_DEV_USER=$DBT_DEV_USER
ENV DBT_DEV_SCHEMA=$DBT_DEV_SCHEMA
ENV DBT_DEV_PORT=$DBT_DEV_PORT
ENV DBT_PROFILES_DIR=.config


WORKDIR /datawarehouse
COPY . .

EXPOSE 8080
RUN pip install -r requirements.txt
RUN dbt deps
RUN dbt docs generate

CMD [ "dbt", "docs", "serve"]