version: 2

sources:
  - name: bank_data
    database: postgres  
    schema: transformed  
    tables:
      - name: customers
        description: 1 dòng là thông tin của 1 khách hàng
        columns:
          - name: customer_id
            test:
              - unique
              - not_null
      - name: transactions
        description: 1 dòng là thông tin về 1 giao dịch của 1 khách hàng
        columns:
          - name: customer_id
            test:
              - unique
              - not_null
          - name: transaction_id
            test:
              - unique
              - not_null